//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPressa
{
    using System;
    using System.Collections.Generic;
    
    public partial class All_Publications
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public All_Publications()
        {
            this.All_Releases = new HashSet<All_Releases>();
        }
    
        public int id { get; set; }
        public string articul { get; set; }
        public string name { get; set; }
        public Nullable<int> id_publication_fk { get; set; }
        public Nullable<int> id_theme_fk { get; set; }
        public Nullable<int> id_publishing_company_fk { get; set; }
        public Nullable<int> id_frequency_fk { get; set; }
        public Nullable<int> id_region_fk { get; set; }
        public Nullable<int> id_edition_fk { get; set; }
        public Nullable<System.DateTime> begin_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<float> price { get; set; }
    
        public virtual Edition Edition { get; set; }
        public virtual Frequency Frequency { get; set; }
        public virtual publication publication { get; set; }
        public virtual publishing_company publishing_company { get; set; }
        public virtual Distribution_region Distribution_region { get; set; }
        public virtual themes themes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<All_Releases> All_Releases { get; set; }
    }
}
