//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPressa
{
    using System;
    using System.Collections.Generic;
    
    public partial class All_Releases
    {
        public int id { get; set; }
        public Nullable<int> id_all_publications_fk { get; set; }
        public Nullable<int> id_release { get; set; }
        public Nullable<System.DateTime> date_release { get; set; }
        public Nullable<int> edition { get; set; }
        public Nullable<int> count_sale { get; set; }
        public Nullable<float> price_release { get; set; }
    
        public virtual All_Publications All_Publications { get; set; }
    }
}
