//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPressa
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class pressDBEntities : DbContext
    {
        public pressDBEntities()
            : base("name=pressDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<All_Publications> All_Publications { get; set; }
        public virtual DbSet<All_Releases> All_Releases { get; set; }
        public virtual DbSet<Distribution_region> Distribution_region { get; set; }
        public virtual DbSet<Edition> Edition { get; set; }
        public virtual DbSet<Frequency> Frequency { get; set; }
        public virtual DbSet<publication> publication { get; set; }
        public virtual DbSet<publishing_company> publishing_company { get; set; }
        public virtual DbSet<themes> themes { get; set; }
        public virtual DbSet<DefineAllPublication> DefineAllPublication { get; set; }
        public virtual DbSet<DefineAllRelease> DefineAllRelease { get; set; }
    
        public virtual ObjectResult<description_all_publications_Result> description_all_publications()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<description_all_publications_Result>("description_all_publications");
        }
    
        public virtual ObjectResult<Description_All_Releases_Result> Description_All_Releases()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Description_All_Releases_Result>("Description_All_Releases");
        }
    }
}
