//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPressa
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetDistributionRegions
    {
        public int id { get; set; }
        public Nullable<int> id_distributionregion_fk { get; set; }
        public Nullable<int> id_region_fk { get; set; }
    
        public virtual Distribution_region Distribution_region { get; set; }
        public virtual Regions Regions { get; set; }
    }
}
