--create database Press;
use Press;
--create table publication
--( [id] int primary key identity(1,1),
--  [name] nvarchar (50),
--  [description] text
--);
--
--insert publication values
--('Газета','Печатное периодическое издание, выходящее не реже одного раза в месяц'),
--('Журнал','Печатное периодическое издание, выходящее не реже одного раза в месяц'),
--('Ежегодник','Печатное периодическое издание, выходящее один раз в год'),
--('Календарь','Печатное издание, выходящее один раз в год'),
--('Бюллетень','Печатное издание, выпускаемое с целью информирования целевой группы людей');
--
--select * from publication;

--create table publishing_company
--(
--[id] int primary key identity(1,1),
--[name] nvarchar(50),
--[city] nvarchar(50),
--[legal_address] text,
--[description] text,
--[director] text
--);
--
--insert publishing_company values
--('Лабиринт', 'Москва','Россия, Москва, ул. Малая Грузинская, 39','','Чудов Николай Николаевич'),
--('Просвещение', 'Москва','Россия, Москва, ул. Большая Грузинская, 93','','Чудинов Николай Николаевич'),
--('Эксмо', 'Москва','Россия, Москва, ул. Средняя Грузинская, 99','','Лудов Николай Николаевич'),
--('Воронеж', 'Воронеж','Россия, Воронеж, ул. Красных партизан, 33','','Курдов Николай Николаевич'),
--('Нижполиграф', 'Нижний Новгород','Россия, Нижний Новгород, ул. Желтого карлика, 9','','Дудов Николай Николаевич');
--
--select * from publishing_company;

--create table Frequency
--( [id] int primary key identity(1,1),
--[description] nvarchar (50)
--);
--
--insert Frequency values
--('ежедневно'),
--('Один раз в неделю по субботам'),
--('Два раза в месяц, в первый и третий вторник'),
--('Один раз в полгода '),
--('По заказу'),
--('Один раз в месяц'),
--('Один раз в год, в декабре');
--
--select * from Frequency;

--create table Edition 
--( [id] int primary key identity(1,1),
--  [count] int 
--);
--
--insert Edition values
-- ( 1000),
-- ( 10000),
-- ( 100000),
-- ( 200000),
-- ( 250000); 
--
-- select * from Edition;

--create table Distribution_region
--( [id] int primary key identity(1,1),
--  [region] text
--);
--
--insert Distribution_region values
--('Россия'),
--('Воронежская область'),
--('Нижегородская область'),
--('не определен');

--select * from Distribution_region;


--create table themes
--(id int primary key identity(1,1),
-- [name] nvarchar(50)
-- );
--
--create table All_Publications
--( [id] int primary key identity(1,1),
--  [articul] nvarchar (50),
--  [name] nvarchar(50),
--  [id_publication_fk] int,
--  foreign key ([id_publication_fk]) references publication (id),
--  [id_theme_fk] int,
--  foreign key (id_theme_fk) references themes(id), 
--  [id_publishing_company_fk] int, 
--  foreign key ([id_publishing_company_fk]) references publishing_company(id),
--  [id_frequency_fk] int,
--  foreign key ([id_frequency_fk]) references frequency(id),
--  [id_region_fk] int,
--  foreign key ([id_region_fk]) references distribution_region(id),
--  [id_edition_fk] int,
--  foreign key ([id_edition_fk]) references edition(id) 
--);
--
--insert themes values
--('Политика'),
--('Для детей'),
--('Сад и огород');
--
--insert All_Publications values
--('A101','Красная заря',1,1,1,1,1,1),
--('B110','Пионерский вестник',1,1,2,3,1,1),
--('C001','Номер один',3,3,1,5,1,5),
--('D010','Ё',3,1,5,5,1,1),
--('N011','Новая',5,3,4,4,1,1),
--('J100','Гениально!',2,2,2,1,1,1);
--
--
--create table All_Prices
--( [id] int primary key identity(1,1),
--  [id_all_publication_fk] int,
--  foreign key ([id_all_publication_fk] ) references all_publications(id),
--  [price_one] real,
--  [date_begin] date,
--  [date_end] date
--);
--
--select * from All_Prices;
--select *from All_publications;


--insert All_Prices values
--(1, 13.75,'2000.1.1', null),
--(1, 3.00, '2000.1.1', '2009.12.31'),
--(1, 5.00, '2010.1.1', '2018.12.31'),
--(1, 7.00, '2019.1.1', null),
--(2,100.05,'2000.1.1', '2019.12.31'),
--(2,130.75,'2020.1.1', null),
--(3,   100,'2020.1.1', null),
--(4,   110,'2020.1.1', null);



--create table All_Releases
--([id] int primary key identity (1,1),
-- [id_all_publications_fk] int,
-- foreign key (id_all_publications_fk) references all_publications(id),
-- [id_release] int,
-- [date_release] date,
-- [edition] int,
-- [price_release] real
--);
--
--
--insert all_releases values
--(6,1,'2000.1.11',1000,13.75),
--(6,2,'2000.2.11',1000,13.75),
--(6,3,'2000.3.11',1000,13.75),
--(6,4,'2000.4.11',1000,13.75),
--(6,5,'2000.5.11',1000,13.75),
--(6,6,'2000.6.11',1000,13.75),
--(6,7,'2000.7.11',1000,13.75);

--select * from edition;

--drop procedure Select_from_date;
--go
--create procedure Select_from_date @dt date
--as
--select a.articul as 'Артикул',
--            p.name as 'Тип Издания',
--            a.name as 'Название',
--            t.name as 'Тема', 
--            f.description as 'Периодичность', 
--            c.city as 'Город', 
--            c.name as 'Издательство', 
--            r.region as 'Доставка', 
--            e.count as 'Тираж', 
--            i.price_one as 'Цена на'+ @dt 
--     from All_Publications as a, publication as p, themes as t, publishing_company as c,frequency as f, 
--          distribution_region as r, edition as e, all_prices as i 
--     where p.id=a.id_publication_fk and t.id=a.id_theme_fk and c.id=a.id_publishing_company_fk and 
--           f.id=a.id_frequency_fk and r.id=a.id_region_fk and e.id=a.id_edition_fk and
--		   i.id_all_publication_fk = a.id 
--		    and
--		      (
--			   ( @dt between i.date_begin and i.date_end          ) or
--			   ((@dt >= i.date_begin) and (i.date_end is null)    ) or
--			   ((@dt <= i.date_end) and (i.date_begin is null)        )  or
--			   ((i.date_begin is null) and (i.date_end is null))
--			  )
--			;

select name from Publication;

--execute Select_from_date @dt='2009.1.1';
 

--go
--create procedure Select_from_date @dt date
--as
--
--select a.articul as 'Артикул',
--            p.name as 'Тип Издания',
--            a.name as 'Название',
--            t.name as 'Тема', 
--            f.description as 'Периодичность', 
--            c.city as 'Город', 
--            c.name as 'Издательство', 
--            r.region as 'Доставка', 
--            e.count as 'Тираж', 
--            i.price_one  as 'Цена' 
--			from All_Publications as a, publication as p, themes as t, publishing_company as c,frequency as f, 
--          distribution_region as r, edition as e, all_prices as i 
--     where p.id=a.id_publication_fk and t.id=a.id_theme_fk and c.id=a.id_publishing_company_fk and 
--           f.id=a.id_frequency_fk and r.id=a.id_region_fk and e.id=a.id_edition_fk and
--		   i.id_all_publication_fk = a.id 
--		    and
--		      (
--			   ( @dt between i.date_begin and i.date_end          ) or
--			   ((@dt >= i.date_begin) and (i.date_end is null)    ) or
--			   ((@dt <= i.date_end) and (i.date_begin is null)        )  or
--			   ((i.date_begin is null) and (i.date_end is null))
--			  )
--			;

--
--go
--create procedure Select_release
--as
--select a.articul as 'Артикул',
--            a.name as 'Название',
--            p.name as 'Тип издания',
--            t.name as 'Тема', 
--            c.name as 'Издательство',
--            r.id_release as 'Номер',
--			r.date_release as 'Дата выпуска',
--			r.edition as 'Продано',
--			r.price_release as 'Цена'
--			from All_Publications as a, publication as p, themes as t, publishing_company as c, All_Releases as r 
--     where p.id=a.id_publication_fk and t.id=a.id_theme_fk and c.id=a.id_publishing_company_fk and 
--            r.id_all_publications_fk=a.id
--			;
--
--drop procedure Select_release;

--go
--create procedure Select_release 
--as
--select a.articul as 'Артикул',
--            a.name as 'Название',
--            p.name as 'Тип издания',
--            t.name as 'Тема', 
--            c.name as 'Издательство',
--            r.id_release as 'Номер',
--			r.date_release as 'Дата выпуска',
--			r.edition as 'Продано',
--			r.price_release as 'Цена'
--			from All_Publications as a, publication as p, themes as t, publishing_company as c, All_Releases as r 
--     where p.id=a.id_publication_fk and t.id=a.id_theme_fk and c.id=a.id_publishing_company_fk and 
--            r.id_all_publications_fk=a.id
--			;
